Map<String, String> countryConverter = {
  "India": "Republic of India",
  "Netherlands": "nederland",
  "United States": "usa"
};

//Implement databases below with countryConverter
Map<String, String> countryNewsConverter = {
  "Afghanistan": "af",
  "Albania": "al",
  "Algeria": "dz",
  "Amercan Samoa": "as",
  "Anguilla": "ai",
  "Australia": "au",
  "Austria": "at",
  "Bahamas": "bs",
  "Bangladesh": "bd",
  "Barbados": "bb",
  "Belarus": "by",
  "Belgium": "be",
  "Belize": "bz",
  "Benin": "bj",
  "Bermuda": "bm",
  "Bhutan": "bt",
  "Bolivia": "bo",
  "Bosnia and Herzegovina": "ba",
  "Bouvet Island": "bv",
  "Brazil": "br",
  "British Indian Ocean Territory": "io",
  "Brunei": "bn",
  "Bulgaria": "bg",
  "Burkina Faso": "bf",
  "Burundi": "bi",
  "Cambodia": "kh",
  "Cameroon": "cm",
  "Canada": "ca",
  "Cape Verde": "cv",
  "Central African Republic": "cf",
  "Chile": "cl",
  "China": "cn",
  "Colombia": "co",
  "Comoros": "km",
  "Congo": "cg",
  "Costa Rica": "cr",
  "Croatia": "hr",
  "Cuba": "cu",
  "Cyprus": "cy",
  "Czech Republic": "cz",
  "Democratic Republic of Congo": "cd",
  "Denmark": "dk",
  "Djibouti": "dj",
  "Dominican Republic": "do",
  "Ecuador": "ec",
  "Egypt": "eg",
  "El Salvador": "sv",
  "Eritrea": "er",
  "Eswatini": "sz",
  "Ethiopia": "et",
  "Fiji": "fj",
  "Finland": "fi",
  "France": "fr",
  "French Guiana": "gf",
  "French Polynesia": "pf",
  "Gambia": "gm",
  "Germany": "de",
  "Ghana": "gh",
  "Greece": "gr",
  "Guatemala": "gt",
  "Guinea": "gn",
  "Guyana": "gy",
  "Honduras": "hn",
  "Hong Kong": "hk",
  "Hungary": "hu",
  "Iceland": "is",
  "India": "in",
  "Indonesia": "id",
  "Iran": "ir",
  "Iraq": "iq",
  "Ireland": "ie",
  "Israel": "il",
  "Italy": "it",
  "Ivory Coast": "ci",
  "Japan": "jp",
  "Jordan": "jo",
  "Kazakhstan": "kz",
  "Kenya": "ke",
  "Kuwait": "kw",
  "Laos": "la",
  "Latvia": "lv",
  "Lebanon": "lb",
  "Lesotho": "ls",
  "Liberia": "lr",
  "Liechtenstein": "li",
  "Lithuania": "lt",
  "Luxembourg": "lu",
  "Macedonia": "mk",
  "Madagascar": "mg",
  "Malawi": "mw",
  "Malaysia": "my",
  "Maldives": "mv",
  "Mali": "ml",
  "Malta": "mt",
  "Mauritania": "mr",
  "Mauritius": "mu",
  "Mexico": "mx",
  "Micronesia": "fm",
  "Moldova": "md",
  "Monaco": "mc",
  "Montenegro": "me",
  "Montserrat": "ms",
  "Morocco": "ma",
  "Mozambique": "mz",
  "Myanmar": "mm",
  "Namibia": "na",
  "Nepal": "np",
  "Netherlands": "nl",
  "New Zealand": "nz",
  "Niger": "ne",
  "Nigeria": "ng",
  "North Korea": "kp",
  "Norway": "no",
  "Oman": "om",
  "Pakistan": "pk",
  "Palestine": "ps",
  "Paraguay": "py",
  "Peru": "pe",
  "Philippines": "ph",
  "Poland": "pl",
  "Portugal": "pt",
  "Puerto Rico": "pr",
  "Qatar": "qa",
  "Romania": "ro",
  "Russia": "ru",
  "Rwanda": "rw",
  "Saint Kitts and Nevis": "kn",
  "Saint Vincent and the Grenadines": "vc",
  "San Marino": "sm",
  "Saudi Arabia": "sa",
  "Senegal": "sn",
  "Serbia": "rs",
  "Seychelles": "sc",
  "Sierra Leone": "sl",
  "Singapore": "sg",
  "Slovakia": "sk",
  "Slovenia": "si",
  "Solomon Islands": "sb",
  "Somalia": "so",
  "South Africa": "za",
  "South Korea": "kr",
  "Spain": "es",
  "Sri Lanka": "lk",
  "Suriname": "sr",
  "Sweden": "se",
  "Switzerland": "ch",
  "Syria": "sy",
  "Taiwan": "tw",
  "Tajikistan": "tj",
  "Thailand": "th",
  "Timor-Leste": "tl",
  "Togo": "tg",
  "Tonga": "to",
  "Trinidad and Tobago": "tt",
  "Turkey": "tr",
  "Tuvalu": "tv",
  "Uganda": "ug",
  "Ukraine": "ua",
  "United Arab Emirates": "ae",
  "United Kingdom": "gb",
  "United States of America": "us",
  "Uruguay": "uy",
  "Uzbekistan": "uz",
  "Vanuatu": "vu",
  "Zambia": "zm",
};

Map<String, String> countryTimezoneConverter = {
  "nederland": "Netherlands",
};

Map<String, String> countryTravelConverter = {
  "British Indian Ocean Territory": "Asia/Thimphu",
  "British Virgin Islands": "America/Manaus",
  "Burkina Faso": "Africa/Monrovia",
  "Cape Verde": "Atlantic/Cape_Verde",
  "Caribbean Netherlands": "America/Manaus",
  "Cayman Islands": "America/Lima",
  "Central African Republic": "Africa/Casablanca",
  "Christmas Island": "Asia/Ho_Chi_Minh",
  "Cocos (Keeling) Islands": "Asia/Yangon",
  "Cook Islands": "Pacific/Honolulu",
  "Dominican Republic": "America/Santo_Domingo",
  "DR Congo": "Africa/Casablanca",
  "El Salvador": "America/El_Salvador",
  "Equatorial Guinea": "Africa/Casablanca",
  "Falkland Islands": "Atlantic/Stanley",
  "Faroe Islands": "Atlantic/Faroe",
  "French Guiana": "America/Paramaribo",
  "French Polynesia": "Pacific/Honolulu",
  "Guadeloupe": "America/Manaus",
  "Guam": "Pacific/Guam",
  "Hong Kong": "Asia/Hong_Kong",
  "Republic of India": "Asia/Kolkata",
  "Isle of Man": "Europe/Dublin",
  "Ivory Coast": "Africa/Abidjan",
  "Marshall Islands": "Pacific/Tarawa",
  "Martinique": "America/Martinique",
  "Mayotte": "Africa/Nairobi",
  "Micronesia": "Australia/Brisbane",
  "Montserrat": "America/Manaus",
  "Nauru": "Pacific/Nauru",
  "nederland": "Europe/Brussels",
  "New Caledonia": "Pacific/Noumea",
  "Niue": "Pacific/Niue",
  "Norfolk Island": "Pacific/Norfolk",
  "Northern Mariana Islands": "Australia/Brisbane",
  "North Korea": "Asia/Pyongyang",
  "Palau": "Pacific/Palau",
  "Palestine": "Asia/Gaza",
  "Papua New Guinea": "Pacific/Port_Moresby",
  "Pitcairn Islands": "Pacific/Pitcairn",
  "Puerto Rico": "America/Puerto_Rico",
  "Republic of the Congo": "Africa/Casablanca",
  "Réunion": "Indian/Mauritius",
  "Saint Barthélemy": "America/Manaus",
  "Saint Helena, Ascension and Tristan da Cunha": "Africa/Abidjan",
  "Saint Kitts and Nevis": "America/Manaus",
  "Saint Lucia": "America/Manaus",
  "Saint Martin": "America/Manaus",
  "Saint Pierre and Miquelon": "America/Miquelon",
  "Saint Vincent and the Grenadines": "America/Manaus",
  "San Marino": "Europe/Rome",
  "São Tomé and Príncipe": "Africa/Sao_Tome",
  "Seychelles": "Indian/Mauritius",
  "Sierra Leone": "Africa/Monrovia",
  "Sint Maarten": "America/Manaus",
  "Solomon Islands": "Pacific/Noumea",
  "South Sudan": "Africa/Juba",
  "Sri Lanka": "Asia/Colombo",
  "Svalbard and Jan Mayen": "Europe/Berlin",
  "Timor-Leste": "Asia/Dili",
  "Tokelau": "Pacific/Apia",
  "Trinidad and Tobago": "America/Manaus",
  "Turkey": "Europe/Istanbul",
  "Turkmenistan": "Asia/Ashgabat",
  "Turks and Caicos Islands": "America/Port-au-Prince",
  "United Arab Emirates": "Asia/Dubai",
  "United Kingdom": "Europe/London",
  "United States Minor Outlying Islands": "Pacific/Apia",
  "United States Virgin Islands": "America/Manaus",
  "Vatican City": "Europe/Rome",
  "Wallis and Futuna": "Pacific/Tarawa",
  "Western Sahara": "Africa/El_Aaiun",
};

Map<String, String> countryWeatherConverter = {
  "Israel": "Jerusalem",
  "Montenegro": "Podgorica",
  "nederland": "Netherlands",
  "Republic of India": "New Delhi",
  "United Kingdom": "London"
};

var timezoneData = {
  "Afghanistan": "Asia/Kabul",
  "Albania": "Europe/Tirane",
  "Algeria": "Africa/Algiers",
  "American Samoa": "Pacific/Pago_Pago",
  "Andorra": "Europe/Andorra",
  "Angola": "Africa/Casablanca",
  "Anguilla": "America/Manaus",
  "Antigua and Barbuda": "America/Manaus",
  "Argentina": "America/Argentina/Buenos_Aires",
  "Armenia": "Asia/Yerevan",
  "Aruba": "America/Manaus",
  "Australia": "Australia/Sydney",
  "Austria": "Europe/Vienna",
  "Azerbaijan": "Asia/Baku",
  "Bahamas": "America/Havana",
  "Bahrain": "Europe/Istanbul",
  "Bangladesh": "Asia/Dhaka",
  "Barbados": "America/Manaus",
  "Belgium": "Europe/Brussels",
  "Belarus": "Europe/Minsk",
  "Belize": "America/Belize",
  "Benin": "Africa/Casablanca",
  "Bermuda": "Atlantic/Bermuda",
  "Bhutan": "Asia/Thimphu",
  "Bolivia": "America/La_Paz",
  "Bosnia and Herzegovina": "Europe/Tirane",
  "Botswana": "Africa/Maputo",
  "Brazil": "America/Sao_Paulo",
  "British Indian Ocean Territory": "Asia/Thimphu",
  "British Virgin Islands": "America/Manaus",
  "Brunei": "Asia/Shanghai",
  "Bulgaria": "Europe/Sofia",
  "Burkina Faso": "Africa/Monrovia",
  "Burundi": "Africa/Maputo",
  "Cambodia": "Asia/Ho_Chi_Minh",
  "Cameroon": "Africa/Casablanca",
  "Canada": "America/New_York",
  "Cape Verde": "Atlantic/Cape_Verde",
  "Caribbean Netherlands": "America/Manaus",
  "Cayman Islands": "America/Lima",
  "Central African Republic": "Africa/Casablanca",
  "Chad": "Africa/Ndjamena",
  "China": "Asia/Shanghai",
  "Chile": "America/Santiago",
  "Christmas Island": "Asia/Ho_Chi_Minh",
  "Cocos (Keeling) Islands": "Asia/Yangon",
  "Colombia": "America/Lima",
  "Comoros": "Africa/Nairobi",
  "Cook Islands": "Pacific/Honolulu",
  "Costa Rica": "America/Costa_Rica",
  "Croatia": "Europe/Tirane",
  "Cuba": "America/Havana",
  "Curaçao": "America/Manaus",
  "Cyprus": "Asia/Nicosia",
  "Czechia": "Europe/Prague",
  "Denmark": "Europe/Berlin",
  "Djibouti": "Africa/Nairobi",
  "Dominica": "America/Santo_Domingo",
  "Dominican Republic": "America/Santo_Domingo",
  "DR Congo": "Africa/Casablanca",
  "Ecuador": "America/Lima",
  "Egypt": "Africa/Cairo",
  "El Salvador": "America/El_Salvador",
  "Equatorial Guinea": "Africa/Casablanca",
  "Eritrea": "Africa/Nairobi",
  "Estonia": "Europe/Tallinn",
  "Eswatini": "Africa/Maputo",
  "Ethiopia": "Africa/Nairobi",
  "Falkland Islands": "Atlantic/Stanley",
  "Faroe Islands": "Atlantic/Faroe",
  "Fiji": "Pacific/Fiji",
  "Finland": "Europe/Helsinki",
  "France": "Europe/Paris",
  "French Guiana": "America/Paramaribo",
  "French Polynesia": "Pacific/Honolulu",
  "Gabon": "Africa/Casablanca",
  "Gambia": "Africa/Monrovia",
  "Georgia": "Asia/Tbilisi",
  "Germany": "Europe/Berlin",
  "Ghana": "Africa/Monrovia",
  "Gibraltar": "Europe/Gibraltar",
  "Greece": "Europe/Athens",
  "Greenland": "America/Nuuk",
  "Grenada": "America/Manaus",
  "Guadeloupe": "America/Manaus",
  "Guam": "Pacific/Guam",
  "Guatemala": "America/Guatemala",
  "Guernsey": "Europe/Dublin",
  "Guinea": "Africa/Monrovia",
  "Guinea-Bissau": "Africa/Bissau",
  "Guyana": "America/Guyana",
  "Haiti": "America/Port-au-Prince",
  "Honduras": "America/Tegucigalpa",
  "Hong Kong": "Asia/Hong_Kong",
  "Hungary": "Europe/Budapest",
  "Iceland": "Africa/Abidjan",
  "Republic of India": "Asia/Kolkata",
  "Indonesia": "Asia/Jakarta",
  "Iran": "Asia/Tehran",
  "Iraq": "Asia/Baghdad",
  "Ireland": "Europe/Dublin",
  "Isle of Man": "Europe/Dublin",
  "Israel": "Asia/Jerusalem",
  "Italy": "Europe/Rome",
  "Ivory Coast": "Africa/Abidjan",
  "Jamaica": "America/Jamaica",
  "Japan": "Asia/Tokyo",
  "Jersey": "Europe/Dublin",
  "Jordan": "Asia/Amman",
  "Kazakhstan": "Asia/Almaty",
  "Kenya": "Africa/Nairobi",
  "Kiribati": "Pacific/Tarawa",
  "Kosovo": "Europe/Tirane",
  "Kuwait": "Europe/Istanbul",
  "Kyrgyzstan": "Asia/Bishkek",
  "Laos": "Asia/Ho_Chi_Minh",
  "Latvia": "Europe/Riga",
  "Lebanon": "Asia/Beirut",
  "Lesotho": "Africa/Maputo",
  "Liberia": "Africa/Monrovia",
  "Libya": "Africa/Tripoli",
  "Liechtenstein": "Europe/Paris",
  "Lithuania": "Europe/Vilnius",
  "Luxembourg": "Europe/Paris",
  "Macau": "Asia/Macau",
  "Madagascar": "Africa/Nairobi",
  "Malawi": "Africa/Maputo",
  "Malaysia": "Asia/Shanghai",
  "Maldives": "Indian/Maldives",
  "Mali": "Africa/Monrovia",
  "Malta": "Europe/Malta",
  "Marshall Islands": "Pacific/Tarawa",
  "Martinique": "America/Martinique",
  "Mauritania": "Africa/Monrovia",
  "Mauritius": "Indian/Mauritius",
  "Mayotte": "Africa/Nairobi",
  "Mexico": "America/Mexico_City",
  "Micronesia": "Australia/Brisbane",
  "Moldova": "Europe/Chisinau",
  "Monaco": "Europe/Paris",
  "Mongolia": "Asia/Ulaanbaatar",
  "Montenegro": "Europe/Tirane",
  "Montserrat": "America/Manaus",
  "Morocco": "Africa/Casablanca",
  "Mozambique": "Africa/Maputo",
  "Myanmar": "Asia/Yangon",
  "Namibia": "Africa/Windhoek",
  "Nauru": "Pacific/Nauru",
  "Nepal": "Asia/Kathmandu",
  "nederland": "Europe/Brussels",
  "New Caledonia": "Pacific/Noumea",
  "New Zealand": "Pacific/Auckland",
  "Nicaragua": "America/Managua",
  "Niger": "Africa/Casablanca",
  "Nigeria": "Africa/Lagos",
  "Niue": "Pacific/Niue",
  "Norfolk Island": "Pacific/Norfolk",
  "Northern Mariana Islands": "Australia/Brisbane",
  "North Korea": "Asia/Pyongyang",
  "North Macedonia": "Europe/Tirane",
  "Norway": "Europe/Berlin",
  "Oman": "Asia/Baku",
  "Pakistan": "Asia/Karachi",
  "Palau": "Pacific/Palau",
  "Palestine": "Asia/Gaza",
  "Panama": "America/Panama",
  "Papua New Guinea": "Pacific/Port_Moresby",
  "Paraguay": "America/Asuncion",
  "Peru": "America/Lima",
  "Philippines": "Asia/Manila",
  "Pitcairn Islands": "Pacific/Pitcairn",
  "Poland": "Europe/Warsaw",
  "Portugal": "Europe/Lisbon",
  "Puerto Rico": "America/Puerto_Rico",
  "Qatar": "Asia/Qatar",
  "Republic of the Congo": "Africa/Casablanca",
  "Romania": "Europe/Bucharest",
  "Russia": "Europe/Moscow",
  "Rwanda": "Africa/Maputo",
  "Réunion": "Indian/Mauritius",
  "Saint Barthélemy": "America/Manaus",
  "Saint Helena, Ascension and Tristan da Cunha": "Africa/Abidjan",
  "Saint Kitts and Nevis": "America/Manaus",
  "Saint Lucia": "America/Manaus",
  "Saint Martin": "America/Manaus",
  "Saint Pierre and Miquelon": "America/Miquelon",
  "Saint Vincent and the Grenadines": "America/Manaus",
  "Samoa": "Pacific/Apia",
  "San Marino": "Europe/Rome",
  "São Tomé and Príncipe": "Africa/Sao_Tome",
  "Saudi Arabia": "Asia/Riyadh",
  "Senegal": "Africa/Monrovia",
  "Serbia": "Europe/Belgrade",
  "Seychelles": "Indian/Mauritius",
  "Sierra Leone": "Africa/Monrovia",
  "Singapore": "Asia/Singapore",
  "Sint Maarten": "America/Manaus",
  "Slovakia": "Europe/Prague",
  "Slovenia": "Europe/Prague",
  "Solomon Islands": "Pacific/Noumea",
  "Somalia": "Africa/Nairobi",
  "South Africa": "Africa/Johannesburg",
  "South Korea": "Asia/Seoul",
  "South Sudan": "Africa/Juba",
  "Spain": "Europe/Madrid",
  "Sri Lanka": "Asia/Colombo",
  "Sudan": "Africa/Khartoum",
  "Suriname": "America/Paramaribo",
  "Svalbard and Jan Mayen": "Europe/Berlin",
  "Sweden": "Europe/Berlin",
  "Switzerland": "Europe/Zurich",
  "Syria": "Asia/Damascus",
  "Taiwan": "Asia/Taipei",
  "Tajikistan": "Asia/Dushanbe",
  "Tanzania": "Africa/Nairobi",
  "Thailand": "Asia/Bangkok",
  "Timor-Leste": "Asia/Dili",
  "Togo": "Africa/Monrovia",
  "Tokelau": "Pacific/Apia",
  "Tonga": "Pacific/Apia",
  "Trinidad and Tobago": "America/Manaus",
  "Tunisia": "Africa/Tunis",
  "Turkey": "Europe/Istanbul",
  "Turkmenistan": "Asia/Ashgabat",
  "Turks and Caicos Islands": "America/Port-au-Prince",
  "Tuvalu": "Pacific/Tarawa",
  "Uganda": "Africa/Nairobi",
  "Ukraine": "Europe/Kyiv",
  "United Arab Emirates": "Asia/Dubai",
  "United Kingdom": "Europe/London",
  "usa": "America/New_York",
  "United States Minor Outlying Islands": "Pacific/Apia",
  "United States Virgin Islands": "America/Manaus",
  "Uruguay": "America/Montevideo",
  "Uzbekistan": "Asia/Tashkent",
  "Vanuatu": "Pacific/Noumea",
  "Vatican City": "Europe/Rome",
  "Venezuela": "America/Caracas",
  "Vietnam": "Asia/Ho_Chi_Minh",
  "Wallis and Futuna": "Pacific/Tarawa",
  "Western Sahara": "Africa/El_Aaiun",
  "Yemen": "Europe/Istanbul",
  "Zambia": "Africa/Maputo",
  "Zimbabwe": "Africa/Maputo",
  "Åland Islands": "Europe/Sofia",
};

//Implement soccerLeagueData wrt countryConverter
Map<String, List> soccerLeagueData = {
  "Belgium": [144],
  "Canada": [258],
  "China": [169],
  "Egypt": [233],
  "France": [61, 62],
  "Germany": [78, 79, 80],
  "India": [323],
  "Italy": [135, 136],
  "Japan": [98],
  "Mexico": [262],
  "Netherlands": [88],
  "Portugal": [94],
  "South Korea": [292],
  "Spain": [140, 141],
  "Turkey": [203],
  "United Kingdom": [39, 40, 41, 42, 180],
  "United States": [253],
};

var countryHolidayConverter = {
  "Andorra": "AD",
  //"United Arab Emirates": "AE",
  //"Antigua and Barbuda": "AG",
  //"Anguilla": "AI",
  "Albania": "AL",
  "Armenia": "AM",
  //"Angola": "AO",
  "Argentina": "AR",
  //"American Samoa": "AS",
  "Austria": "AT",
  "Australia": "AU",
  //"Aruba": "AW",
  "Åland Island": "AX",
  //"Azerbaijan": "AZ",
  "Bosnia and Herzegovina": "BAa",
  "Barbados": "BB",
  //"Bangladesh": "BD",
  "Belgium": "BE",
  //"Burkina Faso": "BF",
  "Bulgaria": "BG",
  //"Bahrain": "BH",
  //"Burundi": "BI",
  "Benin": "BJ",
  //"Saint Barthélemy": "BL",
  //"Bermuda": "BM",
  //"Brunei": "BN",
  "Bolivia": "BO",
  //"Caribbean Netherlands": "BQ",
  "Brazil": "BR",
  "Bahamas": "BS",
  "Botswana": "BW",
  "Belarus": "BY",
  "Belize": "BZ",
  "Canada": "CA",
  //"Cocos (Keeling) Islands": "CC",
  //"Democratic Republic of Congo": "CD",
  //"Central African Republic": "CF",
  //"Republic of Congo": "CG",
  "Switzerland": "CH",
  //"Ivory Coast": "CI",
  //"Cook Islands": "CK",
  "Chile": "CL",
  //"Cameroon": "CM",
  "China": "CN",
  "Colombia": "CO",
  "Costa Rica": "CR",
  "Cuba": "CU",
  //"Cape Verde": "CV",
  //"Curaçao": "CW",
  //"Christmas Island": "CX",
  "Cyprus": "CY",
  "Czech Republic": "CZ",
  "Germany": "DE",
  //"Djibouti": "DJ",
  "Denmark": "DK",
  //"Dominica": "DM",
  "Dominican Republic": "DO",
  //"Algeria": "DZ",
  "Ecuador": "EC",
  "Estonia": "EE",
  "Egypt": "EG",
  //"Western Sahara": "EH",
  //"Eritrea": "ER",
  "Spain": "ES",
  //"Ethiopia": "ET",
  "Finland": "FI",
  //"Fiji": "FJ",
  "Faroe Islands": "FO",
  "France": "FR",
  "Gabon": "GA",
  "United Kingdom": "GB",
  "Grenada": "GD",
  "Georgia": "GE",
  //"French Guiana": "GF",
  "Guernsey": "GG",
  //"Ghana": "GH",
  "Gibraltar": "GI",
  "Greenland": "GL",
  "Gambia": "GM",
  //"Guinea": "GN",
  //"Guadeloupe": "GP",
  //"Equatorial Guinea": "GQ",
  "Greece": "GR",
  "Guatemala": "GT",
  //"Guam": "GU",
  //"Guinea-Bissau": "GW",
  "Guyana": "GY",
  "Hong Kong": "HK",
  "Honduras": "HN",
  "Croatia": "HR",
  "Haiti": "HT",
  "Hungary": "HU",
  //"Canary Islands": "IC",
  "Indonesia": "ID",
  "Ireland": "IE",
  //"Israel": "IL",
  "Isle of Man": "IM",
  //"Iran": "IR",
  "Iceland": "IS",
  "Italy": "IT",
  "Jersey": "JE",
  "Jamaica": "JM",
  "Japan": "JP",
  //"Kenya": "KE",
  //"Comoros": "KM",
  //"Saint Kitts and Nevis": "KN",
  "South Korea": "KR",
  //"Cayman Islands": "KY",
  "Kazakhstan": "KZ",
  //"Saint Lucia": "LC",
  "Lichtenstein": "LI",
  //"Liberia": "LR",
  "Lesotho": "LS",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Latvia": "LV",
  //"Libya": "LY",
  "Morocco": "MA",
  "Monaco": "MC",
  "Moldova": "MD",
  "Montenegro": "ME",
  //"Saint Martin": "MF",
  "Madagascar": "MG",
  "North Macedonia": "MK",
  //"Mali": "ML",
  "Mongolia": "MN",
  //"Martinique": "MQ",
  //"Mauritania": "MR",
  "Montserrat": "MS",
  "Malta": "MT",
  //"Malawi": "MW",
  "Mexico": "MX",
  //"Malaysia": "MY",
  "Mozambique": "MZ",
  "Namibia": "NA",
  //"French Caledonia": "NC",
  "Niger": "NE",
  "Nigeria": "NG",
  "Nicaragua": "NI",
  "nederland": "NL",
  "Norway": "NO",
  "New Zealand": "NZ",
  "Panama": "PA",
  "Peru": "PE",
  "Papua New Guinea": "PG",
  //"Philippines": "PH",
  "Poland": "PL",
  //"Saint Pierre and Miquelon": "PM",
  "Puerto Rico": "PR",
  "Portugal": "PT",
  "Paraguay": "PY",
  //"Réunion": "RE",
  "Romania": "RO",
  "Serbia": "RS",
  "Russia": "RU",
  //"Rwanda": "RW",
  //"Seychelles": "SC",
  //"Sudan": "SD",
  "Sweden": "SE",
  "Singapore": "SG",
  //"Saint Helena, Ascension and Tristan da Cunha": "SH",
  "Slovenia": "SI",
  "Svalbard and Jan Mayen": "SJ",
  "Slovakia": "SK",
  //"Sierra Leone": "SL",
  "San Marino": "SM",
  //"Senegal": "SN",
  //"Somalia": "SO",
  "Suriname": "SR",
  //"South Sudan": "SS",
  //"Sao Tome and Principe": "ST",
  "El Salvador": "SV",
  //"Sint Maarten": "SX",
  //"Eswatini": "SZ",
  //"Turks & Caicos Islands": "TC",
  //"Chad": "TD",
  //"Togo": "TG",
  //"Thailand": "TH",
  "Tunisia": "TN",
  //"Tonga": "TO",
  "Turkey": "TR",
  //"Trinidad and Tobago": "TT",
  //"Taiwan": "TW",
  //"Tanzania": "TZ",
  "Ukraine": "UA",
  //"Uganda": "UG",
  "usa": "US",
  "Uruguay": "UY",
  "Vatican City": "VA",
  //"Saint Vincent and Grenadines": "VC",
  "Venezuela": "VE",
  //"British Virgin Islands": "VG",
  //"United States Virgin Islands": "VI",
  "Vietnam": "VN",
  //"Vanuatu": "VU",
  //"Kosovo": "XK",
  //"Mayotte": "YT",
  "South Africa": "ZA",
  //"Zambia": "ZM",
  "Zimbabwe": "ZW"
};
